server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: descovery
  config:
    import: optional:configserver:http://localhost:8888